# generated by datamodel-codegen:
#   filename:  environment.schema.json
#   timestamp: 2023-08-17T19:53:29+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class EnvironmentSchema(BaseModel):
    JOB_NAME: str = Field(
        ...,
        description='The name of the job that is currently executed.',
        examples=['JOB_NAME', 'bamboo.buildPlanName'],
    )
    JOB_ID: str = Field(
        ...,
        description='The id of the job that is currently executed.',
        examples=['BUILD_ID', 'bamboo.buildNumber'],
    )
    JOB_URI: str = Field(
        ...,
        description='The identifier of the job that is currently executed.',
        examples=['BUILD_TAG', 'bamboo.buildResultKey'],
    )
    JOB_URL: str = Field(
        ...,
        description='The url of the result of the job that is currently executed.',
        examples=['BUILD_URL', 'bamboo.buildResultsUrl'],
    )
    RUNNER_NAME: str = Field(
        ...,
        description='The name of the runner that is executing the job.',
        examples=['NODE_NAME', 'bamboo.agentId'],
    )
    BRANCH_NAME: str = Field(
        ...,
        description='The name of the branch that is currently executed.',
        examples=['BRANCH_NAME', 'bamboo.planRepository.branchName'],
    )
