[tool.mypy]
python_version = "3.11"
check_untyped_defs = true
disallow_untyped_defs = true

[[tool.mypy.overrides]]
# ignore generated classes
module = "classes.generated.*,generated.*"
ignore_errors = true

[tool.black]
force-exclude = '''
    classes/generated
    | venv
    | docs/lib
    | docs/bin
    | docs/source
    '''
line-length = 120

[tool.pylint.'MAIN']

py-version = 3.11
ignore = ['venv', 'generated', 'examples', 'docs']

[tool.pylint.'MESSAGES CONTROL']
max-line-length = 120
min-similarity-lines=10
disable = "missing-module-docstring,missing-class-docstring,missing-function-docstring,too-few-public-methods"