services:
  playground:
    hostname: aeolus-playground
    image: ghcr.io/ls1intum/aeolus/playground:${AEOLUS_DOCKER_TAG:-latest}
    pull_policy: if_not_present
    restart: unless-stopped
  api:
    hostname: aeolus-api
    image: ghcr.io/ls1intum/aeolus/api:${AEOLUS_DOCKER_TAG:-latest}
    pull_policy: if_not_present
    restart: unless-stopped
  bamboo-api:
    hostname: aeolus-bamboo-api
    image: ghcr.io/ls1intum/aeolus/bamboo-generator:${AEOLUS_DOCKER_TAG:-latest}
    command: "--api"
    pull_policy: if_not_present
    restart: unless-stopped
