FROM python:3.11-slim AS cli

RUN apt-get update && apt-get install -y git && rm -rf /var/cache && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

COPY ../../cli/requirements.txt /requirements.txt
RUN pip install -r /requirements.txt && rm /requirements.txt

COPY ../../cli /
RUN rm requirements.txt requirements.in
COPY schemas /schemas
RUN ln -s /main.py /usr/local/bin/aeolus && chmod +x /usr/local/bin/aeolus

ENTRYPOINT ["aeolus"]
CMD ["-h"]