name: Deploy to Aeolus Prod

on:
  workflow_dispatch:
    inputs:
      docker-tag:
        description: 'Docker tag to deploy (e.g. 1.0.0 or latest, default: latest)'
        required: true
        default: 'nightly'
      branch-name:
        description: 'Branch name to deploy (default: develop)'
        required: true
        default: 'develop'

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yaml
    with:
      docker-tag: ${{ github.event.inputs.docker-tag }}
      branch-name: ${{ github.event.inputs.branch-name }}
      environment-name: aeolus-prod
      environment-url: https://aeolus.artemis.cit.tum.de
    secrets: inherit