name: Deploy

on:
  workflow_call:
    inputs:
      docker-tag:
        required: true
        type: string
      branch-name:
        required: true
        type: string
      environment-name:
        required: true
        type: string
      environment-url:
        required: true
        type: string
    secrets:
      DEPLOYMENT_GATEWAY_SSH_KEY:
        required: true

concurrency: deploy

env:
  RAW_URL: https://raw.githubusercontent.com/${{ github.repository }}/${{ github.sha }}


jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: ${{ inputs.environment-name }}
      url: ${{ inputs.environment-url }}

    env:
      DOCKER_TAG: ${{ inputs.docker-tag }}
      BRANCH_NAME: ${{ inputs.branch-name }}
      DEPLOYMENT_USER: ${{ vars.DEPLOYMENT_USER }}
      DEPLOYMENT_HOST: ${{ vars.DEPLOYMENT_HOST }}
      DEPLOYMENT_DIRECTORY: ${{ vars.DEPLOYMENT_DIRECTORY }}
      DEPLOYMENT_HOST_PUBLIC_KEYS: ${{ vars.DEPLOYMENT_HOST_PUBLIC_KEYS }}
      GATEWAY_USER: ${{ vars.GATEWAY_USER }}
      GATEWAY_HOST: ${{ vars.GATEWAY_HOST }}
      GATEWAY_HOST_PUBLIC_KEY: ${{ vars.GATEWAY_HOST_PUBLIC_KEY }}

    steps:
      # Download aeolus-deployment script from GH without cloning the Repository
      - name: Fetch Aeolus Deployment CLI
        run: |
          wget ${{ env.RAW_URL }}/deployment/aeolus-deployment
          wget ${{ env.RAW_URL }}/deployment/aeolus-docker
          chmod +x aeolus-deployment

      # Configure SSH Key
      - name: Setup SSH Keys and known_hosts
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          GATEWAY_SSH_KEY: "${{ secrets.DEPLOYMENT_GATEWAY_SSH_KEY }}"
          DEPLOYMENT_SSH_KEY: "${{ secrets.DEPLOYMENT_SSH_KEY }}"
        run: |
          mkdir -p ~/.ssh
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< $GATEWAY_SSH_KEY
          ssh-add - <<< $DEPLOYMENT_SSH_KEY
          cat - <<< $GATEWAY_HOST_PUBLIC_KEY >> ~/.ssh/known_hosts
          cat - <<< $(sed 's/\\n/\n/g' <<< "$DEPLOYMENT_HOST_PUBLIC_KEYS") >> ~/.ssh/known_hosts

      - name: Prepare directory
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh -J "$GATEWAY_USER@$GATEWAY_HOST" "$DEPLOYMENT_USER@$DEPLOYMENT_HOST" "mkdir -p $DEPLOYMENT_DIRECTORY"

      - name: Copy deployment scripts
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=~/.ssh/known_hosts -o ProxyJump="$GATEWAY_USER@$GATEWAY_HOST" aeolus-docker "$DEPLOYMENT_USER@$DEPLOYMENT_HOST:$DEPLOYMENT_DIRECTORY"

      - name: Deploy Aeolus with Docker
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ./aeolus-deployment docker-deploy "$DEPLOYMENT_USER@$DEPLOYMENT_HOST" -g "$GATEWAY_USER@$GATEWAY_HOST" -t $DOCKER_TAG -b $BRANCH_NAME -d $DEPLOYMENT_DIRECTORY -y