name: Documentation

on:
  pull_request:
    paths:
      - 'docs/**'
      - '.github/workflows/docs.yaml'
  push:
    branches:
      - develop
    paths:
      - 'docs/**'
      - '.github/workflows/docs.yaml'

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ammaraskar/sphinx-action@0.4
        with:
          docs-folder: "docs/"
          build-command: make html dirhtml
      - uses: actions/upload-artifact@v3
        with:
          name: Documentation
          path: docs/_build/html/
      - uses: actions/upload-pages-artifact@v3
        with:
          path: docs/_build/dirhtml/
  # Deployment job
  deploy:
    if: github.ref == 'refs/heads/develop'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: docs
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4