name: CLI Unit tests

on:
  push:
    paths:
      - '**.py'
      - '.github/workflows/python-unit-tests.yaml'

jobs:
  python-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
      - name: Setup Python
        uses: actions/setup-python@v4.7.0
        with:
          python-version: 3.11
      - name: Install Python dependencies
        run: pip install -qr cli/requirements.txt
      - name: Add java jar for bamboo api
        run: |
          apt-get install -y default-jre git
          ./bamboo-generator/gradlew shadowJar --no-daemon -x :generateJsonSchema2Pojo
          cp ./bamboo-generator/libs/bamboo-generator*-all.jar cli/bamboo-generator.jar
      - name: Run tests
        run: |
          cd cli
          python -m unittest
