name: CLI Unit tests

on:
  push:
    paths:
      - '**.py'
      - '.github/workflows/python-unit-tests.yaml'

jobs:
  python-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
      - name: Setup Python
        uses: actions/setup-python@v4.7.0
        with:
          python-version: 3.11
      - name: Install Python dependencies
        run: pip install -qr cli/requirements.txt
      - name: Run tests
        run: |
          cd cli
          python -m unittest
      - name: Generate coverage report
        run: |
          cd cli
          coverage run -m unittest discover
          coverage json
          test_coverage=$(jq ".totals.percent_covered" coverage.json)
          echo "Coverage: $test_coverage"
          if [ $test_coverage -lt 65 ]; then
            echo "Coverage is less than 65%"
            exit 1
          fi
          
