log:
  level: DEBUG
  filePath: /traefik.log
providers:
  docker:
    endpoint: unix:///var/run/docker.sock
  file:
    filename: /traefik-provider.yaml
certificatesResolvers:
  leresolver:
    acme:
      email: letsencrypt@resch.io
      storage: acme.json
      tlsChallenge: {}
entryPoints:
  http:
    address: :80/tcp
    http:
      redirections:
        entrypoint:
          to: https
          scheme: https
  https:
    address: :443/tcp
    http:
      tls:
        certResolver: leresolver
retry: {}